// Compile-time policy boundary between the evolving semantic IR and Markdown representation.

import type {
  AnchoredDrawingRecord,
  EquationSpanRecord,
  HeaderFooterStoryRecord,
  InlineDrawingRecord,
  LineRecord,
  ListMarkerRecord,
  NoteAreaRecord,
  NoteStoryRecord,
  PageRecord,
  ParagraphFragmentRecord,
  SemanticArtifactRootStoryKind,
  SemanticArtifactStoryKind,
  SemanticCommentArtifactRecord,
  SemanticLayout,
  SemanticReviewArtifactOccurrence,
  SemanticReviewArtifactPosition,
  SemanticReviewArtifactSource,
  SemanticTrackedChangeArtifactRecord,
  SourceRange,
  SpanLinkRecord,
  StyleSpanRecord,
  TableCellFragmentRecord,
  TableFragmentRecord,
  TableRowFragmentRecord,
  RevisionAttribution,
  RevisionDisplayMode,
  RevisionKind,
  ResolvedRunStyle,
  SemanticRootStoryKind,
  TextboxStoryLayout,
} from '@docx-editor.dev/core/layout';
import type { ImageResourceState } from '@docx-editor.dev/core/store';

type DrawingAccessibility = InlineDrawingRecord['accessibility'];

type MarkdownFieldPolicy = 'represented' | 'layout-only' | 'explicitly-omitted';

/**
 * `represented` means the translator reads the field to determine emitted Markdown, ordering, or
 * grouping. `layout-only` means its effect is already baked into layout/projection and the
 * translator does not read it. `explicitly-omitted` is an intentional semantic degradation.
 *
 * These maps deliberately enumerate every field consumed at the exporter boundary. A new core
 * semantic field must receive an explicit Markdown policy before TypeScript will pass. Behavioral
 * tests remain the authority for what each represented field emits.
 */
const MARKDOWN_SEMANTIC_POLICY_RATCHETS = Object.freeze({
  span: {
    range: 'represented',
    text: 'represented',
    props: 'explicitly-omitted',
    style: 'represented',
    box: 'layout-only',
    lineEndWhitespace: 'layout-only',
    // A line-end hyphen belongs to one layout width; Markdown text reflows.
    optionalHyphenBreak: 'layout-only',
    caretEdges: 'layout-only',
    tabLeader: 'explicitly-omitted',
    tabLeaderAdvancePt: 'layout-only',
    link: 'represented',
    wrapAdvanceBefore: 'layout-only',
    revisions: 'represented',
    // Simple Markup's margin bar has no Markdown; the revision itself is represented above.
    changeSites: 'explicitly-omitted',
    fieldAtom: 'explicitly-omitted',
    projected: 'layout-only',
    equation: 'represented',
    noteNav: 'represented',
    noteSeparator: 'layout-only',
    fontSlot: 'layout-only',
    glyphOffsetPt: 'layout-only',
    borderBaselinePt: 'layout-only',
    // A view-only content-control tag is never laid out for an export.
    contentControlTag: 'layout-only',
  } satisfies Record<keyof StyleSpanRecord, MarkdownFieldPolicy>,
  sourceRange: {
    paragraphId: 'represented',
    start: 'represented',
    end: 'represented',
  } satisfies Record<keyof SourceRange, MarkdownFieldPolicy>,
  runStyle: {
    fontFamily: 'layout-only',
    fontFamilyEastAsia: 'layout-only',
    latinLane: 'layout-only',
    complexLane: 'layout-only',
    shaping: 'layout-only',
    fontSizePt: 'layout-only',
    color: 'explicitly-omitted',
    bold: 'represented',
    italic: 'represented',
    underline: 'explicitly-omitted',
    strike: 'represented',
    doubleStrike: 'represented',
    highlight: 'explicitly-omitted',
    shading: 'explicitly-omitted',
    verticalAlign: 'explicitly-omitted',
    baselineShiftPt: 'layout-only',
    caps: 'explicitly-omitted',
    smallCaps: 'explicitly-omitted',
    characterSpacingPt: 'layout-only',
    horizontalScalePercent: 'layout-only',
    kerningMinPt: 'layout-only',
    kerningEnabled: 'layout-only',
    ligatures: 'layout-only',
    border: 'explicitly-omitted',
    hidden: 'layout-only',
    textOutline: 'layout-only',
  } satisfies Record<keyof ResolvedRunStyle, MarkdownFieldPolicy>,
  link: {
    id: 'layout-only',
    kind: 'represented',
    href: 'represented',
    anchor: 'explicitly-omitted',
    tooltip: 'explicitly-omitted',
  } satisfies Record<keyof SpanLinkRecord, MarkdownFieldPolicy>,
  equation: {
    sourceNodeId: 'layout-only',
    geometry: 'explicitly-omitted',
    fallbackText: 'represented',
    truncated: 'explicitly-omitted',
  } satisfies Record<keyof EquationSpanRecord, MarkdownFieldPolicy>,
  line: {
    manualBreakAfter: 'layout-only',
    id: 'layout-only',
    range: 'represented',
    spans: 'represented',
    box: 'layout-only',
    contentX: 'layout-only',
    baseline: 'layout-only',
    leading: 'layout-only',
    trailingSpacing: 'layout-only',
    deletedRanges: 'layout-only',
    drawings: 'represented',
    anchorRevisions: 'explicitly-omitted',
    changeSites: 'explicitly-omitted',
  } satisfies Record<keyof LineRecord, MarkdownFieldPolicy>,
  paragraph: {
    kind: 'represented',
    id: 'layout-only',
    paragraphId: 'represented',
    fragmentIndex: 'represented',
    range: 'layout-only',
    props: 'explicitly-omitted',
    styleId: 'layout-only',
    outlineLevel: 'represented',
    alignment: 'represented',
    spacing: 'layout-only',
    indent: 'layout-only',
    bottomBorder: 'explicitly-omitted',
    borders: 'explicitly-omitted',
    shading: 'explicitly-omitted',
    shadingBox: 'layout-only',
    paragraphEnd: 'layout-only',
    emptyParagraphStyle: 'layout-only',
    paragraphMarkSizePt: 'layout-only',
    markRevisions: 'explicitly-omitted',
    markRevision: 'explicitly-omitted',
    markFormatRevision: 'explicitly-omitted',
    markChangeSites: 'explicitly-omitted',
    marker: 'represented',
    tabStops: 'layout-only',
    lines: 'represented',
    box: 'layout-only',
    clipToBox: 'layout-only',
    outOfFlow: 'layout-only',
    positionedFrame: 'layout-only',
  } satisfies Record<keyof ParagraphFragmentRecord, MarkdownFieldPolicy>,
  listMarker: {
    text: 'explicitly-omitted',
    style: 'explicitly-omitted',
    box: 'layout-only',
    level: 'represented',
    numId: 'represented',
    numFmt: 'represented',
    ordinal: 'represented',
    picture: 'layout-only',
    pieces: 'layout-only',
  } satisfies Record<keyof ListMarkerRecord, MarkdownFieldPolicy>,
  table: {
    kind: 'represented',
    id: 'layout-only',
    tableId: 'represented',
    fragmentIndex: 'layout-only',
    nestingDepth: 'layout-only',
    columnEdges: 'represented',
    rows: 'represented',
    box: 'layout-only',
    floatingWrap: 'layout-only',
  } satisfies Record<keyof TableFragmentRecord, MarkdownFieldPolicy>,
  tableRow: {
    id: 'represented',
    revisionKind: 'explicitly-omitted',
    revisionId: 'explicitly-omitted',
    revisionAuthor: 'explicitly-omitted',
    revisionDate: 'explicitly-omitted',
    changeSites: 'explicitly-omitted',
    rowIndex: 'layout-only',
    isHeaderRow: 'represented',
    isHeaderRepeat: 'represented',
    isContinuation: 'layout-only',
    hasContinuation: 'layout-only',
    placesWhole: 'layout-only',
    cells: 'represented',
    box: 'layout-only',
  } satisfies Record<keyof TableRowFragmentRecord, MarkdownFieldPolicy>,
  tableCell: {
    id: 'layout-only',
    gridColumn: 'represented',
    logicalGridColumn: 'represented',
    gridColumnId: 'layout-only',
    gridSpan: 'represented',
    vMergeContinue: 'represented',
    paintInert: 'layout-only',
    textDirection: 'layout-only',
    rowSpan: 'explicitly-omitted',
    shading: 'explicitly-omitted',
    borders: 'explicitly-omitted',
    blocks: 'represented',
    box: 'layout-only',
    revisionShading: 'explicitly-omitted',
    revisionShadingAuthor: 'explicitly-omitted',
  } satisfies Record<keyof TableCellFragmentRecord, MarkdownFieldPolicy>,
  inlineDrawing: {
    kind: 'represented',
    drawingNodeId: 'represented',
    paragraphId: 'represented',
    ownerPartName: 'represented',
    start: 'represented',
    x: 'layout-only',
    y: 'layout-only',
    width: 'represented',
    height: 'represented',
    distL: 'layout-only',
    distR: 'layout-only',
    distT: 'layout-only',
    distB: 'layout-only',
    advanceStart: 'represented',
    advanceEnd: 'layout-only',
    baselineOffset: 'layout-only',
    paintBounds: 'layout-only',
    hitBounds: 'layout-only',
    geometry: 'layout-only',
    resource: 'represented',
    accessibility: 'represented',
    hyperlinkHref: 'explicitly-omitted',
    effects: 'explicitly-omitted',
    crop: 'layout-only',
    transform: 'layout-only',
    placeholderGraphicKind: 'explicitly-omitted',
    vectorShape: 'explicitly-omitted',
    groupPicture: 'explicitly-omitted',
    revisions: 'explicitly-omitted',
    bidiLevel: 'layout-only',
    textboxStory: 'explicitly-omitted',
  } satisfies Record<keyof InlineDrawingRecord, MarkdownFieldPolicy>,
  anchoredDrawing: {
    kind: 'represented',
    drawingNodeId: 'represented',
    paragraphId: 'represented',
    ownerPartName: 'represented',
    start: 'represented',
    x: 'layout-only',
    y: 'layout-only',
    width: 'represented',
    height: 'represented',
    paintBounds: 'layout-only',
    hitBounds: 'layout-only',
    geometry: 'layout-only',
    resource: 'represented',
    accessibility: 'represented',
    hyperlinkHref: 'explicitly-omitted',
    effects: 'explicitly-omitted',
    crop: 'layout-only',
    transform: 'layout-only',
    placeholderGraphicKind: 'explicitly-omitted',
    vectorShape: 'explicitly-omitted',
    groupPicture: 'explicitly-omitted',
    revisions: 'explicitly-omitted',
    bidiLevel: 'layout-only',
    anchorParagraphId: 'layout-only',
    horizontalFrame: 'layout-only',
    verticalFrame: 'layout-only',
    horizontalFrameOrigin: 'layout-only',
    verticalFrameOrigin: 'layout-only',
    behindDocument: 'layout-only',
    allowOverlap: 'layout-only',
    layoutInCell: 'layout-only',
    relativeHeight: 'layout-only',
    wrap: 'layout-only',
    layoutFallback: 'layout-only',
    sourceOrder: 'represented',
    textboxStory: 'explicitly-omitted',
  } satisfies Record<keyof AnchoredDrawingRecord, MarkdownFieldPolicy>,
  drawingAccessibility: {
    hidden: 'explicitly-omitted',
    decorative: 'explicitly-omitted',
    label: 'explicitly-omitted',
  } satisfies Record<keyof DrawingAccessibility, MarkdownFieldPolicy>,
  imageResourceKind: {
    ready: 'layout-only',
    unrenderable: 'layout-only',
    external: 'layout-only',
    missing: 'layout-only',
    pending: 'layout-only',
  } satisfies Record<ImageResourceState['kind'], MarkdownFieldPolicy>,
  textboxStory: {
    fragments: 'explicitly-omitted',
    flowHeight: 'explicitly-omitted',
    contentOffset: 'explicitly-omitted',
    contentWidth: 'explicitly-omitted',
    contentHeight: 'explicitly-omitted',
    fillHex: 'explicitly-omitted',
    strokeHex: 'explicitly-omitted',
    strokeWidthPt: 'explicitly-omitted',
    fallbackReason: 'explicitly-omitted',
    clippedResourceToken: 'layout-only',
  } satisfies Record<keyof TextboxStoryLayout, MarkdownFieldPolicy>,
  page: {
    id: 'layout-only',
    index: 'represented',
    box: 'layout-only',
    contentBox: 'layout-only',
    fragments: 'represented',
    columnSeparators: 'explicitly-omitted',
    pageBorders: 'explicitly-omitted',
    anchoredDrawings: 'represented',
    header: 'represented',
    footer: 'represented',
    footnotes: 'represented',
    endnotes: 'represented',
    noteStream: 'layout-only',
    parityBlank: 'layout-only',
    pageFieldSource: 'layout-only',
    hasBodyPageFields: 'layout-only',
    contentControls: 'explicitly-omitted',
  } satisfies Record<keyof PageRecord, MarkdownFieldPolicy>,
  headerFooter: {
    kind: 'layout-only',
    variant: 'layout-only',
    partName: 'layout-only',
    part: 'layout-only',
    rId: 'layout-only',
    box: 'layout-only',
    fragments: 'represented',
    anchoredDrawings: 'represented',
    pageFieldProjector: 'layout-only',
  } satisfies Record<keyof HeaderFooterStoryRecord, MarkdownFieldPolicy>,
  noteStory: {
    noteKind: 'layout-only',
    noteId: 'layout-only',
    scopeId: 'represented',
    mark: 'layout-only',
    continuation: 'layout-only',
    box: 'layout-only',
    fragments: 'represented',
  } satisfies Record<keyof NoteStoryRecord, MarkdownFieldPolicy>,
  noteSeparator: {
    kind: 'explicitly-omitted',
    box: 'layout-only',
    fragments: 'explicitly-omitted',
    synthetic: 'explicitly-omitted',
    ruleStyle: 'explicitly-omitted',
    ruleColor: 'explicitly-omitted',
  } satisfies Record<keyof NonNullable<NoteAreaRecord['separator']>, MarkdownFieldPolicy>,
  noteArea: {
    kind: 'layout-only',
    placement: 'layout-only',
    box: 'layout-only',
    separator: 'explicitly-omitted',
    continuationNotice: 'explicitly-omitted',
    notes: 'represented',
    fallbackReason: 'explicitly-omitted',
  } satisfies Record<keyof NoteAreaRecord, MarkdownFieldPolicy>,
  layout: {
    revision: 'layout-only',
    displayMode: 'represented',
    pages: 'represented',
    reviewArtifacts: 'represented',
    contentControls: 'explicitly-omitted',
    controlContextToken: 'layout-only',
  } satisfies Record<keyof SemanticLayout, MarkdownFieldPolicy>,
  reviewArtifactOccurrence: {
    pageIndex: 'represented',
    physicalPageNumber: 'represented',
    story: 'represented',
    rootStory: 'represented',
    textboxPath: 'represented',
    noteScopeId: 'represented',
    noteAreaKind: 'represented',
    revisionRole: 'represented',
    source: 'represented',
    geometry: 'layout-only',
  } satisfies Record<keyof SemanticReviewArtifactOccurrence, MarkdownFieldPolicy>,
  reviewArtifactPosition: {
    paragraphId: 'represented',
    offset: 'represented',
  } satisfies Record<keyof SemanticReviewArtifactPosition, MarkdownFieldPolicy>,
  reviewArtifactSource: {
    partName: 'represented',
    start: 'represented',
    end: 'represented',
  } satisfies Record<keyof SemanticReviewArtifactSource, MarkdownFieldPolicy>,
  commentArtifact: {
    kind: 'represented',
    id: 'represented',
    author: 'represented',
    initials: 'represented',
    date: 'represented',
    text: 'represented',
    resolved: 'represented',
    parentId: 'represented',
    parentRevisionId: 'represented',
    replyIds: 'represented',
    orphaned: 'represented',
    occurrences: 'represented',
  } satisfies Record<keyof SemanticCommentArtifactRecord, MarkdownFieldPolicy>,
  trackedChangeArtifact: {
    kind: 'represented',
    id: 'represented',
    change: 'represented',
    markDirection: 'represented',
    author: 'represented',
    date: 'represented',
    text: 'represented',
    replacedText: 'represented',
    nesting: 'represented',
    replacedRangeCount: 'represented',
    readOnly: 'represented',
    pairedWith: 'represented',
    structuralChanges: 'represented',
    replyIds: 'represented',
    occurrences: 'represented',
  } satisfies Record<keyof SemanticTrackedChangeArtifactRecord, MarkdownFieldPolicy>,
  trackedChangeArtifactKind: {
    insert: 'represented',
    delete: 'represented',
    replace: 'represented',
    moveFrom: 'represented',
    moveTo: 'represented',
    format: 'represented',
    paragraphMark: 'represented',
    structural: 'represented',
  } satisfies Record<SemanticTrackedChangeArtifactRecord['change'], MarkdownFieldPolicy>,
  trackedChangeMarkDirection: {
    insert: 'represented',
    delete: 'represented',
    moveFrom: 'represented',
    moveTo: 'represented',
  } satisfies Record<
    NonNullable<SemanticTrackedChangeArtifactRecord['markDirection']>,
    MarkdownFieldPolicy
  >,
  reviewArtifactStoryKind: {
    body: 'represented',
    header: 'represented',
    footer: 'represented',
    footnote: 'represented',
    endnote: 'represented',
    'note-separator': 'represented',
    textbox: 'represented',
  } satisfies Record<SemanticArtifactStoryKind, MarkdownFieldPolicy>,
  reviewArtifactRootStoryKind: {
    body: 'represented',
    header: 'represented',
    footer: 'represented',
    footnote: 'represented',
    endnote: 'represented',
    'note-separator': 'represented',
  } satisfies Record<SemanticArtifactRootStoryKind, MarkdownFieldPolicy>,
  reviewArtifactRevisionRole: {
    replaced: 'represented',
    replacement: 'represented',
    neutral: 'represented',
  } satisfies Record<
    NonNullable<SemanticReviewArtifactOccurrence['revisionRole']>,
    MarkdownFieldPolicy
  >,
  paragraphAlignment: {
    left: 'represented',
    center: 'represented',
    right: 'represented',
    both: 'represented',
  } satisfies Record<ParagraphFragmentRecord['alignment'], MarkdownFieldPolicy>,
  revisionKind: {
    insert: 'explicitly-omitted',
    delete: 'represented',
    moveFrom: 'represented',
    moveTo: 'explicitly-omitted',
    format: 'explicitly-omitted',
  } satisfies Record<RevisionKind, MarkdownFieldPolicy>,
  revisionAttribution: {
    kind: 'represented',
    id: 'explicitly-omitted',
    author: 'explicitly-omitted',
    date: 'explicitly-omitted',
    nodeId: 'explicitly-omitted',
  } satisfies Record<keyof RevisionAttribution, MarkdownFieldPolicy>,
  revisionDisplayMode: {
    'all-markup': 'represented',
    proposed: 'represented',
    original: 'represented',
  } satisfies Record<RevisionDisplayMode, MarkdownFieldPolicy>,
  noteNavigationDirection: {
    'to-note': 'represented',
    'to-body': 'represented',
  } satisfies Record<NonNullable<StyleSpanRecord['noteNav']>['direction'], MarkdownFieldPolicy>,
  linkKind: {
    external: 'represented',
    internal: 'explicitly-omitted',
    unresolved: 'explicitly-omitted',
  } satisfies Record<SpanLinkRecord['kind'], MarkdownFieldPolicy>,
  rootStoryKind: {
    body: 'represented',
    header: 'represented',
    footer: 'represented',
    footnote: 'represented',
    endnote: 'represented',
    'note-separator': 'explicitly-omitted',
  } satisfies Record<SemanticRootStoryKind, MarkdownFieldPolicy>,
});

void MARKDOWN_SEMANTIC_POLICY_RATCHETS;
